[[comments]]
date = 2007-12-17T09:27:22Z
name = "topher"
link = "http://topher.88-mph.net/"
message = """
Hi Mikong!

I'm excited about the Rails community. Hopefully we can have a monthly meetup starting on January.

The events you listed are all the PHRUG events so far."""
