[[comments]]
date = 2007-11-14T09:06:06Z
name = "Ryan Tani"
link = "http://www.ryantani.com/"
message = """
Great news! Really looking forward to reading more from you. Got my slicehost this week, too. Thinking about moving from blogger to wordpress. Anyway goodluck on your blog."""

[[comments]]
date = 2007-11-14T10:08:44Z
name = "Tin"
message = """
That's great Mike! Can't wait for your next post!"""

[[comments]]
date = 2007-11-16T11:02:45Z
name = "Ria Jose"
link = "http://workwithria.wordpress.com/"
message = """
Really good and really interesting post. I expect (and other readers maybe :)) new useful posts from you!
Good luck and successes in blogging!"""

[[comments]]
date = 2007-12-15T12:28:20Z
name = "Idetrorce"
message = """
very interesting, but I don't agree with you
Idetrorce"""

[[comments]]
date = 2007-12-15T13:34:03Z
name = "mikong"
message = """
@ldetrorce - Thanks for the comment. Just wondering, what is it that you don't agree with? Slicehost as a great VPS hosting company, the prepayment for the long term, or perhaps the Wordpress over Mephisto choice?"""
