[[comments]]
date = 2007-12-26T06:53:36Z
name = "farleyknight"
link = "http://blog.chaosmeme.com/"
message = """
Interesting. What type of keyboard are you using? A blank one I bet..."""

[[comments]]
date = 2007-12-26T08:34:25Z
name = "mikong"
message = """
I didn't modify the keys of my macbook. I have a transparent keyboard protector but that's it."""
