[[comments]]
date = 2008-02-19T15:41:01Z
name = "topher"
link = "http://blog.admoolabs.com/"
message = """
The end of Rails?

Of course not! :)

I haven't tried Groovy yet, and I don't think I'll ever have the time to try it. There are other great developments in the Ruby world, like Merb and other Ruby web frameworks, Rubinius, and JRuby."""
