[[comments]]
date = 2008-07-29T09:38:08Z
name = "Joseph Wilk"
link = "http://www.joesniff.co.uk/"
message = """
You are not alone. Go is a brilliant game. I’ve always liked the idea that to play Go better it is recommended you try to solve 'life and death' problems. I have to face life and death problems everyday programming :)"""
