[[comments]]
date = 2008-11-12T03:27:09Z
name = "bob"
message = """
How does the login process work?

How can i detect a logged in user like Rails' logged_in?"""

[[comments]]
date = 2008-11-12T03:27:41Z
name = "bob"
message = """
When i say \"How does the login process work?\", i mean \"How does the user login?\""""

[[comments]]
date = 2008-11-12T12:07:04Z
name = "mikong"
message = """
The standard Merb stack already provides an accessible login page thru /login. You can detect if the user is logged in with \"session.authenticated?\"."""

[[comments]]
date = 2008-12-10T18:59:22Z
name = "scott"
link = "http://scottmotte.com/"
message = """
Thanks mikong. This was a good help."""
