[[comments]]
date = 2008-05-22T11:24:30Z
name = "Frank"
link = "http://behindhiddendoors.wordpress.com/"
message = """
Holy Crap, you're a celebrity now? I've been gone a long time!

Glad to see you're doing more than well. Keep up!"""

[[comments]]
date = 2008-05-24T08:06:28Z
name = "mikong"
message = """
Hey Frank, I haven't heard from you in a long time.

A celebrity? PHRUG monthly meetups aren't big. I had about 10 people listening to my talk. And I volunteered for this. It's not like they were requesting for some guru to speak. But I learned a lot, and I hope the audience learned as well. Also, the coding session was fun!"""
